import { useEffect, useMemo, useState, type ChangeEvent, type ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Activity, Cloud, Download, Eye, EyeOff, FileCheck2, FolderOpen, HardDrive, KeyRound, Link2, Lock, MoreHorizontal, RefreshCw, Search, ShieldCheck, Trash2, Upload, Wallet, Wifi, Zap } from "lucide-react";
import { toast } from "sonner";
import { connectWalletWithWalletConnect } from "./walletConnect";
import { clearAuthUser, finishGoogleLoginFromUrl, getSavedAuthUser, loginWithWalletAddress, startGoogleLogin, type AuthUser } from "./authSystem";

type P2PChannel = "p2p:start" | "p2p:listFiles" | "p2p:upload" | "p2p:download" | "p2p:delete" | "p2p:networkSummary" | "p2p:bootstrapNow" | "p2p:connectPeer" | "p2p:repair" | "p2p:prepareProof" | "wallet:status" | "wallet:connect" | "wallet:disconnect" | "wallet:setPlan" | "electron:openDevTools" | "electron:diagnostics";
type ElectronBridge = { invoke: <T>(channel: P2PChannel, payload?: unknown) => Promise<T>; isElectron?: boolean; platform?: string };
type WalletPlan = { id: string; name: string; quotaBytes: number; priceUsd: number; locked?: boolean };
type WalletState = { ok: boolean; connected: boolean; address: string; planId: string; connectedAt?: string | null; paidUntil?: number | null; subscriptionTx?: string | null; plan: WalletPlan; plans: WalletPlan[]; usedBytes: number; remainingBytes: number };
type P2PFile = { id: string; name: string; size: number; hash: string; rootHash: string; uploadedAt: string; isEncrypted: boolean; mimeType?: string; totalChunks: number; ownerNodeId: string; ownerWallet?: string; planId?: string; replicas: string[] };
type P2PPeer = { peerId: string; url?: string; status?: string; lastSeen?: string | number };
type P2PSummary = { ok: boolean; peerId: string; port: number; host: string; listenUrl: string; peers: P2PPeer[]; connectedPeers: number; targetReplicas: number; totalFiles: number; encryptedFiles: number; publicFiles: number; totalBytes: number; totalChunks: number; underReplicatedChunks: number; wallet?: WalletState };
type DownloadResult = { ok: boolean; file: P2PFile; bytes: number[] };
type RepairResult = { report: Array<{ file: string; chunkIndex: number; healthyReplicas: string[]; targetReplicas: number; underReplicated: boolean }> };
type PendingPayPal = { orderId: string; planId: string; approveUrl?: string };

type WalletConnectResult = { address: string; loginMessage?: string; signature?: string };

declare global { interface Window { electron?: ElectronBridge } }

const PAYPAL_SERVER_BASE = import.meta.env.VITE_PAYPAL_SERVER_BASE || "http://127.0.0.1:8791";

function getElectronBridge(): ElectronBridge | null { return typeof window !== "undefined" && typeof window.electron?.invoke === "function" ? window.electron : null; }
function formatBytes(bytes = 0) { if (bytes >= 1024 ** 4) return `${(bytes / 1024 ** 4).toFixed(2)} TB`; if (bytes >= 1024 ** 3) return `${(bytes / 1024 ** 3).toFixed(2)} GB`; if (bytes >= 1024 ** 2) return `${(bytes / 1024 ** 2).toFixed(2)} MB`; if (bytes >= 1024) return `${(bytes / 1024).toFixed(2)} KB`; return `${bytes} B`; }
function formatDate(value?: string | number | null) { if (!value) return "unknown"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "unknown" : date.toLocaleString(); }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : "Operation failed"; }
function shortAddress(address = "") { return address ? `${address.slice(0, 6)}...${address.slice(-4)}` : "Not connected"; }

function ElectronRequiredScreen() {
  return <div className="min-h-screen bg-zinc-950 p-6 text-zinc-50"><Card className="mx-auto mt-16 max-w-2xl rounded-2xl border-red-900 bg-zinc-900"><CardHeader><CardTitle>Electron preload bridge is missing</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-zinc-300"><p>This app must run inside Electron so storage stays on the native encrypted P2P path.</p><pre className="overflow-auto rounded-xl bg-zinc-950 p-3 text-xs">git pull{"\n"}pnpm run electron:dev</pre></CardContent></Card></div>;
}

function StatCard({ icon, label, value, sub }: { icon: ReactNode; label: string; value: string | number; sub?: string }) {
  return <Card className="rounded-2xl border-zinc-800 bg-zinc-900/80"><CardContent className="flex items-center gap-4 p-5"><div className="rounded-2xl bg-zinc-800 p-3 text-zinc-100">{icon}</div><div className="min-w-0"><p className="text-sm text-zinc-400">{label}</p><p className="truncate text-xl font-semibold text-zinc-50">{value}</p>{sub && <p className="mt-0.5 truncate text-xs text-zinc-500">{sub}</p>}</div></CardContent></Card>;
}

export default function NativeP2PApp() {
  const bridge = getElectronBridge();
  const [summary, setSummary] = useState<P2PSummary | null>(null);
  const [wallet, setWallet] = useState<WalletState | null>(null);
  const [files, setFiles] = useState<P2PFile[]>([]);
  const [repairReport, setRepairReport] = useState<RepairResult["report"]>([]);
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [isEncrypted, setIsEncrypted] = useState(true);
  const [drivePassword, setDrivePassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [peerId, setPeerId] = useState("");
  const [peerUrl, setPeerUrl] = useState("");
  const [search, setSearch] = useState("");
  const [busy, setBusy] = useState(false);
  const [walletConnecting, setWalletConnecting] = useState(false);
  const [advancedMode, setAdvancedMode] = useState(false);
  const [authUser, setAuthUser] = useState<AuthUser | null>(() => getSavedAuthUser());
  const [pendingPayPal, setPendingPayPal] = useState<PendingPayPal | null>(() => { try { const raw = localStorage.getItem("peercloud.pending.paypal"); return raw ? JSON.parse(raw) : null; } catch { return null; } });

  if (!bridge) return <ElectronRequiredScreen />;

  const selectedBytes = useMemo(() => selectedFiles.reduce((sum, file) => sum + file.size, 0), [selectedFiles]);
  const walletConnected = Boolean(wallet?.connected && wallet.address);
  const quotaPercent = wallet?.plan?.quotaBytes ? Math.min(100, (wallet.usedBytes / wallet.plan.quotaBytes) * 100) : 0;
  const uploadWouldExceedQuota = Boolean(wallet && selectedBytes > 0 && wallet.usedBytes + selectedBytes > wallet.plan.quotaBytes);
  const visibleFiles = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return files; return files.filter((file) => [file.name, file.hash, file.rootHash, file.ownerWallet || ""].some((value) => value.toLowerCase().includes(query))); }, [files, search]);

  const refreshAll = async () => {
    const [nextSummary, nextFiles, nextWallet] = await Promise.all([bridge.invoke<P2PSummary>("p2p:networkSummary"), bridge.invoke<P2PFile[]>("p2p:listFiles", { query: search }), bridge.invoke<WalletState>("wallet:status")]);
    setSummary(nextSummary); setFiles(Array.isArray(nextFiles) ? nextFiles : []); setWallet(nextWallet);
  };
  const runBusy = async (work: () => Promise<void>) => { setBusy(true); try { await work(); } catch (error) { toast.error(errorMessage(error)); } finally { setBusy(false); } };

  useEffect(() => { void runBusy(async () => { await bridge.invoke("p2p:start"); await refreshAll(); }); }, []);
  useEffect(() => { finishGoogleLoginFromUrl().then((user) => { if (user) { setAuthUser(user); toast.success(`Signed in as ${user.displayName}`); } }).catch((error) => toast.error(errorMessage(error))); }, []);

  const connectWallet = async () => {
    if (walletConnecting) return;
    setWalletConnecting(true);
    try {
      const timeout = new Promise<never>((_, reject) => setTimeout(() => reject(new Error("Wallet connection cancelled or timed out.")), 30000));
      const result = await Promise.race([connectWalletWithWalletConnect(), timeout]) as WalletConnectResult;
      const nextWallet = await bridge.invoke<WalletState>("wallet:connect", { address: result.address, loginMessage: result.loginMessage, signature: result.signature });
      setWallet(nextWallet);
      setAuthUser(loginWithWalletAddress(result.address));
      toast.success("Wallet connected");
      await refreshAll();
    } catch (error) { toast.error(errorMessage(error)); } finally { setWalletConnecting(false); }
  };

  const disconnectWallet = () => runBusy(async () => { const nextWallet = await bridge.invoke<WalletState>("wallet:disconnect"); setWallet(nextWallet); localStorage.removeItem("peercloud.pending.paypal"); setPendingPayPal(null); toast.success("Wallet disconnected"); await refreshAll(); });
  const logoutAuth = () => { clearAuthUser(); setAuthUser(null); toast.success("Signed out"); };
  const setPlan = (planId: string) => runBusy(async () => { const nextWallet = await bridge.invoke<WalletState>("wallet:setPlan", { planId }); setWallet(nextWallet); toast.success(`Plan switched to ${nextWallet.plan.name}`); await refreshAll(); });
  const copyPaymentLink = async (url?: string) => { if (!url) throw new Error("No PayPal payment link available"); await navigator.clipboard.writeText(url); toast.success("Payment link copied"); };
  const payWithPayPal = (plan: WalletPlan) => runBusy(async () => { if (!walletConnected || !wallet?.address) throw new Error("Connect wallet before payment"); const response = await fetch(`${PAYPAL_SERVER_BASE}/api/paypal/create-order`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ wallet: wallet.address, planId: plan.id }) }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || "PayPal create-order failed"); const pending = { orderId: data.orderId, planId: plan.id, approveUrl: data.approveUrl }; localStorage.setItem("peercloud.pending.paypal", JSON.stringify(pending)); setPendingPayPal(pending); await copyPaymentLink(data.approveUrl); toast.success("PayPal order created"); });
  const confirmPayPal = () => runBusy(async () => { if (!pendingPayPal) throw new Error("No pending PayPal order"); const response = await fetch(`${PAYPAL_SERVER_BASE}/api/paypal/capture-order`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ orderId: pendingPayPal.orderId }) }); const data = await response.json(); if (!response.ok || !data.ok || !data.subscription) throw new Error(data.error || "PayPal capture failed"); const sub = data.subscription; const nextWallet = await bridge.invoke<WalletState>("wallet:setPlan", { planId: sub.planId, paidUntil: sub.paidUntil, quotaBytes: sub.quotaBytes, contractPlanId: Number(String(sub.planId).replace(/\D/g, "")) || 1, txHash: sub.captureId }); setWallet(nextWallet); localStorage.removeItem("peercloud.pending.paypal"); setPendingPayPal(null); toast.success(`${nextWallet.plan.name} unlocked`); await refreshAll(); });

  const handleFileSelect = (event: ChangeEvent<HTMLInputElement>) => setSelectedFiles(Array.from(event.target.files || []));
  const getDrivePassword = () => { if (!isEncrypted) return null; const password = drivePassword.trim(); if (password.length < 6) throw new Error("Enter your Drive Password for encrypted files."); return password; };
  const uploadFiles = () => runBusy(async () => { if (!walletConnected) throw new Error("Connect your wallet before uploading"); if (uploadWouldExceedQuota) throw new Error("Storage quota exceeded. Upgrade your plan."); if (!selectedFiles.length) throw new Error("Select at least one file"); const password = getDrivePassword(); for (const file of selectedFiles) await bridge.invoke("p2p:upload", { name: file.name, mimeType: file.type || "application/octet-stream", isEncrypted, drivePassword: password, bytes: await file.arrayBuffer() }); setSelectedFiles([]); toast.success("Files stored safely"); await refreshAll(); });
  const downloadFile = (file: P2PFile) => runBusy(async () => { const password = file.isEncrypted ? getDrivePassword() : null; const result = await bridge.invoke<DownloadResult>("p2p:download", { hash: file.hash, drivePassword: password }); const blob = new Blob([new Uint8Array(result.bytes)], { type: result.file.mimeType || "application/octet-stream" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.file.name; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); toast.success("Download verified"); });
  const deleteFile = (file: P2PFile) => runBusy(async () => { await bridge.invoke("p2p:delete", { hash: file.hash }); toast.success("File removed"); await refreshAll(); });
  const connectPeer = () => runBusy(async () => { await bridge.invoke("p2p:connectPeer", { peerId, url: peerUrl }); setPeerId(""); setPeerUrl(""); toast.success("Peer connection started"); await refreshAll(); });
  const repair = () => runBusy(async () => { const result = await bridge.invoke<RepairResult>("p2p:repair"); setRepairReport(Array.isArray(result.report) ? result.report : []); await refreshAll(); });
  const prepareProof = (file: P2PFile) => runBusy(async () => { const result = await bridge.invoke<{ proof: unknown }>("p2p:prepareProof", { hash: file.hash }); await navigator.clipboard.writeText(JSON.stringify(result.proof, null, 2)); toast.success("Proof copied"); });

  return <div className="min-h-screen bg-zinc-950 text-zinc-50">
    <header className="border-b border-zinc-800 bg-zinc-950"><div className="container flex flex-col gap-4 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><div className="rounded-2xl bg-zinc-50 p-3 text-zinc-950"><Cloud className="size-7" /></div><div><h1 className="text-2xl font-semibold">p2p.cloud Drive</h1><p className="mt-1 text-sm text-zinc-400">Encrypted storage that follows your wallet.</p></div></div><div className="flex flex-wrap gap-2"><Badge variant={walletConnected ? "default" : "secondary"} className="px-3 py-2">{walletConnected ? <Wallet className="mr-1 size-4" /> : <Lock className="mr-1 size-4" />}{walletConnected ? shortAddress(wallet?.address) : "Guest view"}</Badge><Button variant="outline" onClick={() => void runBusy(refreshAll)} disabled={busy}><RefreshCw className="size-4" />Refresh</Button><Button variant={advancedMode ? "default" : "outline"} onClick={() => setAdvancedMode((value) => !value)}><MoreHorizontal className="size-4" />{advancedMode ? "Simple" : "Advanced"}</Button></div></div></header>

    <main className="container grid gap-6 py-6 lg:grid-cols-[260px_minmax(0,1fr)]">
      <aside className="space-y-4"><Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardContent className="space-y-4 p-5"><div><p className="text-sm text-zinc-400">Account</p><p className="mt-1 truncate font-medium">{authUser?.displayName || (walletConnected ? shortAddress(wallet?.address) : "Guest")}</p></div><div className="flex flex-col gap-2">{walletConnected ? <Button variant="outline" onClick={disconnectWallet} disabled={busy}>Disconnect Wallet</Button> : <Button onClick={() => void connectWallet()} disabled={walletConnecting}><Wallet className="size-4" />{walletConnecting ? "Connecting..." : "Connect Wallet"}</Button>}{!authUser && <Button variant="outline" onClick={startGoogleLogin} disabled={busy}>Google</Button>}{authUser && <Button variant="ghost" onClick={logoutAuth}>Logout</Button>}</div></CardContent></Card><Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardContent className="space-y-3 p-5"><div className="flex items-center justify-between text-sm"><span className="text-zinc-400">Storage</span><span>{quotaPercent.toFixed(0)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-zinc-50" style={{ width: `${quotaPercent}%` }} /></div><p className="text-xs text-zinc-400">{formatBytes(wallet?.usedBytes ?? 0)} of {formatBytes(wallet?.plan?.quotaBytes ?? 0)} · {wallet?.plan?.name || "Free"}</p></CardContent></Card><nav className="grid gap-2 text-sm"><div className="rounded-xl bg-zinc-900 px-4 py-3 font-medium"><FolderOpen className="mr-2 inline size-4" />My Files</div><div className="rounded-xl px-4 py-3 text-zinc-400"><ShieldCheck className="mr-2 inline size-4" />Encrypted by default</div>{advancedMode && <div className="rounded-xl px-4 py-3 text-zinc-400"><Wifi className="mr-2 inline size-4" />Network Lab</div>}</nav></aside>

      <section className="space-y-6"><section className="grid gap-3 md:grid-cols-4"><StatCard icon={<FolderOpen className="size-5" />} label="Files" value={summary?.totalFiles ?? 0} sub={`${summary?.encryptedFiles ?? 0} encrypted`} /><StatCard icon={<HardDrive className="size-5" />} label="Used" value={formatBytes(summary?.totalBytes ?? 0)} sub={`Remaining ${formatBytes(wallet?.remainingBytes ?? 0)}`} /><StatCard icon={<ShieldCheck className="size-5" />} label="Protection" value={isEncrypted ? "Encrypted" : "Public"} sub="Drive password required" /><StatCard icon={<Wifi className="size-5" />} label="Network" value={`${summary?.connectedPeers ?? 0} peers`} sub={summary?.underReplicatedChunks ? `${summary.underReplicatedChunks} need repair` : "Healthy"} /></section>

        {pendingPayPal && <Card className="rounded-2xl border-amber-800 bg-amber-950/40"><CardContent className="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold text-amber-100">Pending PayPal payment</p><p className="break-all text-sm text-amber-200/80">Order: {pendingPayPal.orderId}</p></div><div className="flex flex-wrap gap-2"><Button onClick={confirmPayPal} disabled={busy}>Confirm Payment</Button>{pendingPayPal.approveUrl && <Button variant="outline" onClick={() => void runBusy(async () => copyPaymentLink(pendingPayPal.approveUrl))}>Copy Link</Button>}<Button variant="ghost" onClick={() => { localStorage.removeItem("peercloud.pending.paypal"); setPendingPayPal(null); }}>Cancel</Button></div></CardContent></Card>}

        <Tabs defaultValue="files" className="space-y-5"><TabsList className="rounded-2xl border border-zinc-800 bg-zinc-900 p-1"><TabsTrigger value="files">My Files</TabsTrigger><TabsTrigger value="upload">Upload</TabsTrigger><TabsTrigger value="plans">Plans</TabsTrigger>{advancedMode && <TabsTrigger value="advanced">Advanced</TabsTrigger>}</TabsList>
          <TabsContent value="files" className="space-y-4"><div className="flex flex-col gap-3 rounded-2xl border border-zinc-800 bg-zinc-900 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-zinc-500" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your drive" className="pl-9" /></div><Button variant="outline" onClick={() => void runBusy(refreshAll)} disabled={busy}>Search</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visibleFiles.map((file) => <Card key={file.hash} className="rounded-2xl border-zinc-800 bg-zinc-900"><CardContent className="space-y-4 p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><div className="rounded-2xl bg-zinc-800 p-3"><FileCheck2 className="size-5" /></div><div className="min-w-0"><h2 className="truncate font-semibold">{file.name}</h2><p className="mt-1 text-sm text-zinc-400">{formatBytes(file.size)} · {formatDate(file.uploadedAt)}</p></div></div>{file.isEncrypted && <Badge variant="secondary"><Lock className="mr-1 size-3" />Encrypted</Badge>}</div>{advancedMode && <div className="space-y-1 rounded-xl bg-zinc-950 p-3 text-xs text-zinc-500"><p className="break-all">hash: {file.hash}</p><p className="break-all">root: {file.rootHash}</p><p className="break-all">wallet: {file.ownerWallet || "legacy/local"}</p><p>{file.totalChunks} chunk(s) · {file.replicas?.length || 0} replica(s)</p></div>}<div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => downloadFile(file)} disabled={busy}><Download className="size-4" />Download</Button>{advancedMode && <Button variant="outline" size="sm" onClick={() => prepareProof(file)} disabled={busy}><ShieldCheck className="size-4" />Proof</Button>}<Button variant="destructive" size="sm" onClick={() => deleteFile(file)} disabled={busy}><Trash2 className="size-4" />Delete</Button></div></CardContent></Card>)}</div>{visibleFiles.length === 0 && <Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardContent className="py-14 text-center"><FolderOpen className="mx-auto size-10 text-zinc-500" /><p className="mt-4 font-medium">Your drive is empty</p><p className="mt-1 text-sm text-zinc-400">Upload your first encrypted file to start syncing across devices.</p></CardContent></Card>}</TabsContent>

          <TabsContent value="upload"><Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardHeader><CardTitle className="flex items-center gap-2"><Upload className="size-5" />Upload encrypted files</CardTitle></CardHeader><CardContent className="space-y-5">{!walletConnected && <div className="rounded-2xl border border-zinc-700 bg-zinc-950 p-4 text-sm text-zinc-300">Connect your wallet to unlock encrypted storage. Guest view stays open.</div>}<Input type="file" multiple onChange={handleFileSelect} disabled={!walletConnected || busy} /><div className="grid gap-4 lg:grid-cols-2"><label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><Checkbox checked={isEncrypted} onCheckedChange={(value) => setIsEncrypted(Boolean(value))} disabled={!walletConnected} /><span><span className="block font-medium">Encrypted storage</span><span className="text-sm text-zinc-400">Recommended. Peers store encrypted chunks only.</span></span></label><div className="space-y-2 rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><Label htmlFor="drive-password" className="flex items-center gap-2"><KeyRound className="size-4" />Drive Password</Label><div className="flex gap-2"><Input id="drive-password" type={showPassword ? "text" : "password"} value={drivePassword} onChange={(event) => setDrivePassword(event.target.value)} placeholder="Needed for encrypted upload/download" disabled={!walletConnected || !isEncrypted} /><Button type="button" variant="outline" onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</Button></div></div></div><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-zinc-400">Selected: {selectedFiles.length} file(s), {formatBytes(selectedBytes)}</p><Button onClick={uploadFiles} disabled={busy || !walletConnected || selectedFiles.length === 0 || uploadWouldExceedQuota}><Zap className="size-4" />Store files</Button></div>{uploadWouldExceedQuota && <p className="rounded-xl border border-red-900 bg-red-950/40 p-3 text-sm text-red-200">Selected files exceed your plan. Upgrade before upload.</p>}</CardContent></Card></TabsContent>

          <TabsContent value="plans"><Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardHeader><CardTitle>Storage plans</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{(wallet?.plans || []).map((plan) => <button key={plan.id} onClick={() => plan.locked ? payWithPayPal(plan) : setPlan(plan.id)} disabled={busy || !walletConnected} className={`rounded-2xl border p-4 text-left transition ${wallet?.planId === plan.id ? "border-zinc-50 bg-zinc-800" : "border-zinc-800 bg-zinc-950 hover:bg-zinc-900"}`}><p className="font-semibold">{plan.name}</p><p className="mt-2 text-sm text-zinc-400">{formatBytes(plan.quotaBytes)}</p><p className="mt-1 text-sm">${plan.priceUsd}/month</p></button>)}</CardContent></Card></TabsContent>

          {advancedMode && <TabsContent value="advanced" className="space-y-5"><Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardHeader><CardTitle>Advanced network controls</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void runBusy(async () => { await bridge.invoke("p2p:bootstrapNow"); await refreshAll(); })} disabled={busy}><Link2 className="size-4" />Connect Network</Button><Button onClick={repair} disabled={busy}><ShieldCheck className="size-4" />Fix Storage</Button><Button variant="outline" onClick={() => bridge.invoke("electron:openDevTools")}><Activity className="size-4" />DevTools</Button></div><div className="grid gap-3 lg:grid-cols-2"><Input value={peerId} onChange={(event) => setPeerId(event.target.value)} placeholder="Peer id" /><Input value={peerUrl} onChange={(event) => setPeerUrl(event.target.value)} placeholder="ws://peer:8787" /></div><Button onClick={connectPeer} disabled={busy || !peerId || !peerUrl}>Connect peer</Button></CardContent></Card><div className="grid gap-5 lg:grid-cols-2"><Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardHeader><CardTitle>Devices / Peers</CardTitle></CardHeader><CardContent className="space-y-3">{(summary?.peers || []).map((peer) => <div key={peer.peerId} className="rounded-xl border border-zinc-800 bg-zinc-950 p-3"><p className="break-all text-sm font-medium">{peer.peerId}</p><p className="break-all text-xs text-zinc-500">{peer.url || "Direct socket"}</p><Badge className="mt-2" variant={peer.status === "connected" ? "default" : "secondary"}>{peer.status || "known"}</Badge></div>)}{(summary?.peers || []).length === 0 && <p className="text-sm text-zinc-400">No peers connected.</p>}</CardContent></Card><Card className="rounded-2xl border-zinc-800 bg-zinc-900"><CardHeader><CardTitle>Storage health</CardTitle></CardHeader><CardContent className="space-y-3"><Button onClick={repair} disabled={busy}><Activity className="size-4" />Scan now</Button>{repairReport.map((item) => <div key={`${item.file}-${item.chunkIndex}`} className="rounded-xl border border-zinc-800 bg-zinc-950 p-3"><p className="text-sm font-medium">{item.file} chunk #{item.chunkIndex}</p><p className="text-xs text-zinc-400">{item.healthyReplicas.length}/{item.targetReplicas} replicas</p></div>)}{repairReport.length === 0 && <p className="text-sm text-zinc-400">No scan results yet.</p>}</CardContent></Card></div></TabsContent>}
        </Tabs>
      </section>
    </main>
  </div>;
}
