@echo off
echo Starting P2P Storage Browser Enhanced...
echo.
echo 1. Installing dependencies...
call pnpm install
echo.
echo 2. Starting Frontend on http://127.0.0.1:3000 ...
start cmd /k "pnpm vite --host 127.0.0.1 --port 3000"
echo.
echo 3. Starting Backend Server...
pnpm run server
pause
