import { app, BrowserWindow, Menu, Tray, nativeImage } from 'electron';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const APP_TITLE = 'Chunknet';
const IS_DEV_WRAPPER = !app.isPackaged || Boolean(process.env.ELECTRON_RENDERER_URL);
let tray = null;
let isQuitting = false;
let closeNoticeShown = false;
let mainImportStarted = false;

console.log('[main-wrapper] starting', { isPackaged: app.isPackaged, rendererUrl: process.env.ELECTRON_RENDERER_URL || null, dev: IS_DEV_WRAPPER });
const gotSingleInstanceLock = IS_DEV_WRAPPER ? true : app.requestSingleInstanceLock();
console.log('[main-wrapper] single-instance lock', gotSingleInstanceLock);
if (!gotSingleInstanceLock) { console.warn('[main-wrapper] another instance owns the lock; exiting this instance'); app.exit(0); } else { app.on('second-instance', () => { console.log('[main-wrapper] second instance requested'); showMainWindow(); }); }
function isVirtualInterfaceName(name = '') { const n = String(name).toLowerCase(); return ['hyper-v','vethernet','virtual','vmware','virtualbox','docker','wsl','loopback','bluetooth','npcap','tap','tun'].some((bad) => n.includes(bad)); }
function scoreIp(ip = '') { if (ip.startsWith('192.168.')) return 100; if (ip.startsWith('10.')) return 80; if (/^172\.(1[6-9]|2\d|3[0-1])\./.test(ip)) return 60; return 10; }
function chooseLanAddress() { const candidates = []; const nets = os.networkInterfaces(); for (const [name, items] of Object.entries(nets)) { if (isVirtualInterfaceName(name)) continue; for (const net of items || []) { if (!net || net.internal || net.family !== 'IPv4') continue; const ip = net.address; if (!ip || ip.startsWith('127.') || ip.startsWith('169.254.')) continue; candidates.push({ ip, name, score: scoreIp(ip) }); } } candidates.sort((a, b) => b.score - a.score); return candidates[0]?.ip || '127.0.0.1'; }
function configureNetworkRuntime() { const port = process.env.P2P_TRANSPORT_PORT || '8787'; if (!process.env.P2P_CHUNK_SIZE_BYTES) process.env.P2P_CHUNK_SIZE_BYTES = String(2 * 1024 * 1024); if (!process.env.P2P_UPLOAD_CONCURRENCY) process.env.P2P_UPLOAD_CONCURRENCY = '4'; if (!process.env.P2P_DOWNLOAD_CONCURRENCY) process.env.P2P_DOWNLOAD_CONCURRENCY = '6'; if (!process.env.P2P_AUTO_REPAIR_INTERVAL_MS) process.env.P2P_AUTO_REPAIR_INTERVAL_MS = String(3 * 60 * 60 * 1000); if (!process.env.P2P_AUTO_REPAIR_START_DELAY_MS) process.env.P2P_AUTO_REPAIR_START_DELAY_MS = String(5 * 60 * 1000); if (!process.env.P2P_PROTECTION_RETRY_INTERVAL_MS) process.env.P2P_PROTECTION_RETRY_INTERVAL_MS = String(5 * 60 * 1000); if (!process.env.P2P_PROTECTION_RETRY_START_DELAY_MS) process.env.P2P_PROTECTION_RETRY_START_DELAY_MS = String(45 * 1000); if (!process.env.P2P_PUBLIC_URL && !process.env.VITE_P2P_PUBLIC_URL) { const ip = chooseLanAddress(); process.env.P2P_PUBLIC_URL = `ws://${ip}:${port}`; console.log('[runtime] selected public peer URL:', process.env.P2P_PUBLIC_URL); } if (!process.env.P2P_CHUNK_STORE_DIR) { process.env.P2P_CHUNK_STORE_DIR = path.join(app.getPath('userData'), 'native-p2p-storage', 'chunks'); console.log('[runtime] selected chunk store:', process.env.P2P_CHUNK_STORE_DIR); } console.log('[runtime] transfer defaults:', { chunkSizeBytes: process.env.P2P_CHUNK_SIZE_BYTES, uploadConcurrency: process.env.P2P_UPLOAD_CONCURRENCY, downloadConcurrency: process.env.P2P_DOWNLOAD_CONCURRENCY, autoRepairIntervalMs: process.env.P2P_AUTO_REPAIR_INTERVAL_MS, autoRepairStartDelayMs: process.env.P2P_AUTO_REPAIR_START_DELAY_MS, protectionRetryIntervalMs: process.env.P2P_PROTECTION_RETRY_INTERVAL_MS, protectionRetryStartDelayMs: process.env.P2P_PROTECTION_RETRY_START_DELAY_MS }); }
function resolveTrayIcon() { const candidates = [path.join(__dirname, '..', 'assets', 'icon.ico'), path.join(__dirname, '..', 'assets', 'icon.png')]; const found = candidates.find((candidate) => fs.existsSync(candidate)); if (!found) return nativeImage.createEmpty(); const image = nativeImage.createFromPath(found); return image.isEmpty() ? nativeImage.createEmpty() : image; }
function showMainWindow() { const win = globalThis.__p2pCloudMainWindow; if (!win || win.isDestroyed()) { console.warn('[main-wrapper] show requested but no main window exists'); return; } win.show(); if (win.isMinimized()) win.restore(); win.focus(); console.log('[main-wrapper] main window shown'); }
function createFallbackWindow(reason = 'main window did not appear') { if (globalThis.__p2pCloudMainWindow && !globalThis.__p2pCloudMainWindow.isDestroyed()) return; console.warn('[main-wrapper] fallback window created:', reason); const win = new BrowserWindow({ title: APP_TITLE, width: 1280, height: 820, minWidth: 980, minHeight: 680, show: true, backgroundColor: '#09090b', webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: false } }); globalThis.__p2pCloudMainWindow = win; const url = process.env.ELECTRON_RENDERER_URL || 'http://127.0.0.1:3000'; win.loadURL(url).catch((error) => { console.error('[main-wrapper] fallback loadURL failed:', error?.message || error); }); win.show(); win.focus(); }
function createTray() { if (tray) return tray; tray = new Tray(resolveTrayIcon()); tray.setToolTip(`${APP_TITLE} — running securely in the background`); tray.setContextMenu(Menu.buildFromTemplate([{ label: 'Open Chunknet', click: showMainWindow }, { type: 'separator' }, { label: 'Secure storage is running', enabled: false }, { label: 'Close window keeps protection online', enabled: false }, { type: 'separator' }, { label: 'Quit Chunknet', click: () => { isQuitting = true; app.quit(); } }])); tray.on('double-click', showMainWindow); return tray; }
function mainStableHasP2PHandlers() { try { const src = fs.readFileSync(path.join(__dirname, 'main-stable.js'), 'utf8'); return src.includes("ipcMain.handle('p2p:start'") && src.includes("ipcMain.handle('p2p:networkSummary'"); } catch { return false; } }
async function importPrimaryRuntime() { if (!mainStableHasP2PHandlers()) { console.warn('[main-wrapper] main-stable.js lacks p2p handlers; importing complete main.js runtime'); await import('./main.js'); console.log('[main-wrapper] main.js fallback import finished'); return 'main'; } try { await import('./main-stable.js'); console.log('[main-wrapper] main-stable.js import finished'); return 'main-stable'; } catch (error) { console.error('[main-wrapper] main-stable.js import failed, trying complete main.js:', error?.stack || error?.message || error); await import('./main.js'); console.log('[main-wrapper] main.js fallback import finished'); return 'main'; } }
async function importMainWhenReady() { if (mainImportStarted) return; mainImportStarted = true; console.log('[main-wrapper] importing runtime after app ready'); try { await import('./p2p-transport-global-registry.js'); console.log('[main-wrapper] p2p global registry import finished'); await importPrimaryRuntime(); await import('./company-workspace-ipc.js'); console.log('[main-wrapper] company workspace IPC import finished'); await import('./company-offline-invite-ipc.js'); console.log('[main-wrapper] company offline invite IPC import finished'); await import('./company-distributed-objects-ipc.js'); console.log('[main-wrapper] company distributed objects IPC import finished'); await import('./seed-auth-cooldown-ipc.js'); console.log('[main-wrapper] seed auth cooldown IPC import finished'); await import('./protected-upload-override.js'); console.log('[main-wrapper] protected upload status override import finished'); await import('./stream-upload-override.js'); console.log('[main-wrapper] streaming upload override import finished'); await import('./protection-retry-loop.js'); console.log('[main-wrapper] protection retry loop import finished'); await import('./download-to-path-override.js'); console.log('[main-wrapper] download override import finished'); setTimeout(() => createFallbackWindow('runtime imported but no BrowserWindow appeared'), 3000); } catch (error) { console.error('[main-wrapper] import failed:', error?.stack || error?.message || error); createFallbackWindow(error?.message || 'Electron startup import failed'); } }
app.on('ready', () => { console.log('[main-wrapper] app ready'); configureNetworkRuntime(); createTray(); });
app.on('browser-window-created', (_event, win) => { console.log('[main-wrapper] browser window created'); globalThis.__p2pCloudMainWindow = win; setTimeout(() => { try { win.show(); if (win.isMinimized()) win.restore(); win.focus(); console.log('[main-wrapper] forced window show'); } catch (error) { console.warn('[main-wrapper] force window show failed:', error?.message || error); } }, 1200); win.on('close', (event) => { if (isQuitting) return; if (IS_DEV_WRAPPER) return; event.preventDefault(); win.hide(); createTray(); if (!closeNoticeShown && tray) { closeNoticeShown = true; tray.displayBalloon?.({ title: APP_TITLE, content: 'Chunknet is still running in the background to keep your storage available.' }); } }); });
app.on('before-quit', () => { isQuitting = true; });
if (gotSingleInstanceLock) { console.log('[main-wrapper] scheduling runtime import after app ready'); app.whenReady().then(importMainWhenReady).catch((error) => { console.error('[main-wrapper] app.whenReady failed:', error?.stack || error?.message || error); createFallbackWindow(error?.message || 'app.whenReady failed'); }); }
